My Project: SymTable Class Reference
SymTable Class Reference
class for a symbol table mapping the strings which are the values of variables to integers representing those strings
#include <SymTable.h>
Public Member Functions
SymTable (void)
int get_code (string cat)
this adds word to the sym table if it is not there
int check_code (string cat)
this looks word up and returns -1 if it is not in the table
string decode_to_symbol (int code)
goes back from a code to the original string symbol
Public Attributes
int symbol_total
the total number of symbols in the table
map< string, int > the_symbols
Private Attributes
map< int, string > sym_decoder
Detailed Description
class for a symbol table mapping the strings which are the values of variables to integers representing those strings
Definition at line 12 of file SymTable.h.
Constructor & Destructor Documentation
SymTable()
SymTable::SymTable (void)
Definition at line 10 of file SymTable.cpp.
Member Function Documentation
check_code()
int SymTable::check_code (string cat)
this looks word up and returns -1 if it is not in the table
Definition at line 37 of file SymTable.cpp.
decode_to_symbol()
string SymTable::decode_to_symbol (int code)
goes back from a code to the original string symbol
Definition at line 49 of file SymTable.cpp.
Referenced by main(), CoinTrial::outcomes_string(), and CoinTrial::show().
get_code()
int SymTable::get_code (string cat)
this adds word to the sym table if it is not there
Definition at line 18 of file SymTable.cpp.
Referenced by process_corpus().
Member Data Documentation
sym_decoder
map<int,string> SymTable::sym_decoder private
Definition at line 24 of file SymTable.h.
symbol_total
int SymTable::symbol_total
the total number of symbols in the table
Definition at line 16 of file SymTable.h.
the_symbols
map<string,int> SymTable::the_symbols
Definition at line 21 of file SymTable.h.
The documentation for this class was generated from the following files:
SymTable.h
SymTable.cpp