My Project: make_gamma.cpp File Reference
make_gamma.cpp File Reference
#include "SymTable.h"
#include "CoinTrial.h"
#include "Variable.h"
#include "prob_tables_coin.h"
#include <iostream>
#include <fstream>
#include <algorithm>
Functions
void process_corpus (string file)
turn contents of filename into cdata each line of the file is represented by a CoinTrial object
void tokenize (string line, vector< string > &words)
splits a line into into tokens using white-space as separator
int main (int argc, char **argv)
Variables
Variable chce
encapsulates the 'disk' being used to choose a type of coin. contains symbol table for its possible outcomes (eg. A vs B)
Variable ht
encapsulates a heads-vs-tails coin toss. contain symbol table for its possible outcomes (eg. H vs T)
vector< CoinTrial > cdata
represents all the data as a vector of CoinTrial objects
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 27 of file make_gamma.cpp.
References cdata, chce, chce_probs, SymTable::decode_to_symbol(), ht_probs, process_corpus(), and Variable::table.
process_corpus()
void process_corpus (string file)
turn contents of filename into cdata each line of the file is represented by a CoinTrial object
Definition at line 82 of file make_gamma.cpp.
References cdata, chce, CoinTrial::coin_choice, SymTable::get_code(), ht, CoinTrial::outcomes, Variable::table, and tokenize().
Referenced by main().
tokenize()
void tokenize (string line, vector< string > & words)
splits a line into into tokens using white-space as separator
Definition at line 128 of file make_gamma.cpp.
Referenced by process_corpus().
Variable Documentation
cdata
vector<CoinTrial> cdata
represents all the data as a vector of CoinTrial objects
Definition at line 17 of file make_gamma.cpp.
Referenced by main(), and process_corpus().
chce
Variable chce
encapsulates the 'disk' being used to choose a type of coin. contains symbol table for its possible outcomes (eg. A vs B)
Definition at line 12 of file make_gamma.cpp.
Referenced by main(), process_corpus(), and CoinTrial::show().
ht
Variable ht
encapsulates a heads-vs-tails coin toss. contain symbol table for its possible outcomes (eg. H vs T)
Definition at line 14 of file make_gamma.cpp.
Referenced by CoinTrial::outcomes_string(), process_corpus(), and CoinTrial::show().